package com.ciq.sms.quries;

public interface StudentQueries {
	String STUDENT_INSERT_QUERY= "INSERT INTO STUDENT(SID, SNAME, SFEE) VALUES (?,?,?)";
	String STUDENT_UPDATE_QUERY= "UPDATE STUDENT SET SNAME=?, SFEE=?,WHERE  SID=? ";
	String STUDENT_DELETE_QUERY="DELETE FROM STUDENT WHERE SID= ?";
	String STUDENT_FINDALL_QUERY= "SELECT * FROM STUDENT";
	String STUDENT_FINDBY_ID_QUERY= "SELECT * FROM STUDENT WHERE SID=? ";
	String STUDENT_FINDBY_NAME_QUERY= "SELECT * FROM STUDENT WHERE SNAME=?";
	


}
